name: city3d
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - requests
  - tqdm
  - shapely
  - fiona
  - pdal
  - python-pdal
  - trimesh
  - pyvista
  - rasterio
  - scikit-spatial 
  - pip:
    - open3d
